#include "lwip/def.h"
// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[] = "ed91eef5-f2af-43ee-91a0-0e01ee3ec4d2";

const char SSID[] = SECRET_SSID;              // Network SSID (name)
const char PASS[] = SECRET_OPTIONAL_PASS;     // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[] = SECRET_DEVICE_KEY;  // Secret device password

void onSp02Change();
void onBpmChange();
void onTemperatureChange();
void onMedicineChange();
void onFallDetectionChange();

CloudDataRate SP02;
CloudHeartRate BPM;
CloudTemperatureSensor Temperature;
CloudSchedule Medicine;
bool Fall_Detection;

void initProperties() {

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(SP02, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(BPM, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(Temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(Medicine, READWRITE, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(Fall_Detection, READ, ON_CHANGE, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

const unsigned char epd_bitmap_network_16x8 [] PROGMEM = {
	0x00, 0x03, //               ##
	0x00, 0x0f, //             ####
	0x00, 0x3f, //           ######
	0x00, 0xff, //         ########
	0x03, 0xff, //       ##########
	0x0f, 0xff, //     ############
	0x3f, 0xff, //   ##############
	0xff, 0xff  // ################
};
