// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ed91eef5-f2af-43ee-91a0-0e01ee3ec4d2";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSp02Change();
void onBpmChange();
void onTemperatureChange();
void onMedicineChange();
void onFallDetectionChange();

CloudDataRate SP02;
CloudHeartRate BPM;
CloudTemperatureSensor Temperature;
CloudSchedule Medicine;
bool Fall_Detection;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(SP02, READWRITE, ON_CHANGE, onSp02Change);
  ArduinoCloud.addProperty(BPM, READWRITE, ON_CHANGE, onBpmChange);
  ArduinoCloud.addProperty(Temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(Medicine, READWRITE, ON_CHANGE, onMedicineChange);
  ArduinoCloud.addProperty(Fall_Detection, READWRITE, ON_CHANGE, onFallDetectionChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
